//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.13 at 09:17:53 PM VET 
//


package com.unisigma.epbd.consultarcarteraafiliadoperiodo;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.unisigma.epbd.consultarcarteraafiliadoperiodo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.unisigma.epbd.consultarcarteraafiliadoperiodo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultarCarteraAfiliadoPorPeriodoRequest }
     * 
     */
    public ConsultarCarteraAfiliadoPorPeriodoRequest createConsultarCarteraAfiliadoPorPeriodoRequest() {
        return new ConsultarCarteraAfiliadoPorPeriodoRequest();
    }

    /**
     * Create an instance of {@link ConsultarCarteraAfiliadoPorPeriodoOutput }
     * 
     */
    public ConsultarCarteraAfiliadoPorPeriodoOutput createConsultarCarteraAfiliadoPorPeriodoOutput() {
        return new ConsultarCarteraAfiliadoPorPeriodoOutput();
    }

    /**
     * Create an instance of {@link RespuestaCarteraAfiliadoType }
     * 
     */
    public RespuestaCarteraAfiliadoType createRespuestaCarteraAfiliadoType() {
        return new RespuestaCarteraAfiliadoType();
    }

    /**
     * Create an instance of {@link RespuestaPaginacionType }
     * 
     */
    public RespuestaPaginacionType createRespuestaPaginacionType() {
        return new RespuestaPaginacionType();
    }

}
