//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.13 at 09:17:53 PM VET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.unisigma.com/epbd/ConsultarCarteraAfiliadoPeriodo", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.unisigma.epbd.consultarcarteraafiliadoperiodo;
