//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.13 at 09:17:53 PM VET 
//


package com.unisigma.epbd.consultarcarteraafiliadoperiodo;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RespuestaCarteraAfiliadoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RespuestaCarteraAfiliadoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="solicitudId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="nss" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="primerApellido" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="estadoAfiliacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="motivoEstadoId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="fechaEfectividadAfiliacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RespuestaCarteraAfiliadoType", propOrder = {
    "solicitudId",
    "nss",
    "nombre",
    "primerApellido",
    "estadoAfiliacion",
    "motivoEstadoId",
    "fechaEfectividadAfiliacion"
})
public class RespuestaCarteraAfiliadoType {

    protected long solicitudId;
    protected Integer nss;
    protected String nombre;
    protected String primerApellido;
    protected String estadoAfiliacion;
    protected Integer motivoEstadoId;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaEfectividadAfiliacion;

    /**
     * Gets the value of the solicitudId property.
     * 
     */
    public long getSolicitudId() {
        return solicitudId;
    }

    /**
     * Sets the value of the solicitudId property.
     * 
     */
    public void setSolicitudId(long value) {
        this.solicitudId = value;
    }

    /**
     * Gets the value of the nss property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNss() {
        return nss;
    }

    /**
     * Sets the value of the nss property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNss(Integer value) {
        this.nss = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the primerApellido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimerApellido() {
        return primerApellido;
    }

    /**
     * Sets the value of the primerApellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimerApellido(String value) {
        this.primerApellido = value;
    }

    /**
     * Gets the value of the estadoAfiliacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoAfiliacion() {
        return estadoAfiliacion;
    }

    /**
     * Sets the value of the estadoAfiliacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoAfiliacion(String value) {
        this.estadoAfiliacion = value;
    }

    /**
     * Gets the value of the motivoEstadoId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMotivoEstadoId() {
        return motivoEstadoId;
    }

    /**
     * Sets the value of the motivoEstadoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMotivoEstadoId(Integer value) {
        this.motivoEstadoId = value;
    }

    /**
     * Gets the value of the fechaEfectividadAfiliacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaEfectividadAfiliacion() {
        return fechaEfectividadAfiliacion;
    }

    /**
     * Sets the value of the fechaEfectividadAfiliacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaEfectividadAfiliacion(XMLGregorianCalendar value) {
        this.fechaEfectividadAfiliacion = value;
    }

}
