package hexagonaldemo.repositories;

import hexagonaldemo.entity.ExcepcionParametroRequeridoIntercambioInformacionEntity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ExcepcionParametroRequeridoIntercambioInformacionRep extends JpaRepository<ExcepcionParametroRequeridoIntercambioInformacionEntity, Long> {
}
